name: Setup base
description: Setup base

runs:
  using: 'composite'
  steps:
    - name: Setup wm
      shell: bash
      run: |
        mkdir -p $(pwd)/apps/usr/local/bin
        echo "$(pwd)/apps/usr/local/bin" >> $GITHUB_PATH
        cd wm
        chmod +x config.sh
        ./config.sh
        echo "$(pwd)" >> $GITHUB_PATH

    - name: Set up dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dotnet wasm tools
      shell: bash
      run: |
        dotnet workload install wasm-tools
